### PR TITLE
Add PHP7 compatibility

### PR DESCRIPTION
**Pull request by lucascourot**
Fixes https://github.com/DevLyon/mixter/issues/35

Update laravel and phpunit dependencies to the PHP7 compatible versions

### CODE REVIEW

**Comment by fpellet** [comment]
Thank you! Sorry for this delay.
I will integrate this update in php/v2.1, but laravel 5.0 don't work with php 7.2, because mcrypt is removed.
You can update laravel? I don't know this framework, and I have some incomprehensible mistakes :(

**Comment by devcrafting** [comment]
working on laravel 5.1 update (enough to remove mcrypt dependency)

**Comment by devcrafting** [comment]
Hello Lucas,

Thanks, we did the update for DDDEurope. Could you check it is ok (just the beginning at least)? It works with the Docker (dockerfile provided for PHP 7.2).

Thanks and sorry for the delay.

**Comment by lucascourot** [comment]
Hello,

@devcrafting I just tried on my laptop and it works fine with php7.1 👍

**Pull request closed without merging**
